import type { CapabilityContract } from './contracts';

const schemaObject = (properties: Record<string, unknown>, required: string[] = []): Record<string, unknown> => ({
  type: 'object',
  properties,
  required,
  additionalProperties: false,
});

export const AGENT_CORE_V2_BASELINE_CAPABILITIES: readonly CapabilityContract[] = [
  {
    contractVersion: 1,
    id: 'workspace.create_file',
    name: 'create_file',
    title: 'Criar arquivo',
    category: 'workspace',
    description: 'Cria um novo arquivo de texto no workspace real. Diretórios pais ausentes são criados automaticamente. A operação deve ser atômica, verificada e registrada no Recovery Journal.',
    whenToUse: [
      'Quando o resultado exige um novo arquivo conhecido.',
      'Quando criar o primeiro arquivo também pode materializar a estrutura de diretórios pais.',
    ],
    whenNotToUse: [
      'Não usar para substituir silenciosamente arquivo existente.',
      'Não usar shell redirection quando esta capability representa a operação.',
    ],
    inputSchema: schemaObject({
      path: { type: 'string' },
      content: { type: 'string' },
    }, ['path', 'content']),
    outputSchema: schemaObject({
      path: { type: 'string' },
      hash: { type: 'string' },
      bytes: { type: 'number' },
    }, ['path', 'hash', 'bytes']),
    examples: [
      'Criar Desktop/Carros/index.html com o HTML inicial.',
      'Criar src/components/Hero.tsx; src/components é criado automaticamente se não existir.',
    ],
    failureModes: [
      'Path fora do escopo permitido.',
      'Arquivo destino já existe quando overwrite não foi explicitamente permitido.',
      'Falha de escrita atômica ou verificação pós-write.',
    ],
    sideEffects: ['Cria o arquivo no workspace real e pode criar diretórios pais.'],
    annotations: { readOnly: false, destructive: false, idempotent: false, openWorld: false },
    requiresWorkspace: true,
    supportsRollback: true,
    supportsParallel: true,
    resourceLocks: ['path:{path}', 'parent-chain:{path}'],
    permissionClass: 'write',
    activity: {
      running: 'Criando {path}',
      completed: 'Criado {path}',
      failed: 'Falha ao criar {path}',
    },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'workspace.create_folder',
    name: 'create_folder',
    title: 'Criar pasta',
    category: 'workspace',
    description: 'Cria uma pasta real no workspace quando o diretório em si faz parte do resultado ou precisa existir vazio. Não substitui create_file, que continua criando diretórios pais automaticamente.',
    whenToUse: [
      'Quando o usuário pediu explicitamente uma pasta.',
      'Quando uma pasta vazia é parte do resultado.',
      'Quando uma etapa posterior depende da existência explícita do diretório antes de criar arquivos.',
    ],
    whenNotToUse: [
      'Não chamar apenas para preparar diretórios pais de create_file.',
      'Não usar mkdir via shell quando esta capability representa a intenção.',
    ],
    inputSchema: schemaObject({ path: { type: 'string' } }, ['path']),
    outputSchema: schemaObject({ path: { type: 'string' }, created: { type: 'boolean' } }, ['path', 'created']),
    examples: [
      'Criar assets/uploads como pasta vazia.',
      'Criar Desktop/Carros antes de abrir a pasta a pedido do usuário.',
    ],
    failureModes: [
      'Path fora do escopo.',
      'Conflito com arquivo existente.',
      'Falha de filesystem/verificação.',
    ],
    sideEffects: ['Cria um diretório no workspace real.'],
    annotations: { readOnly: false, destructive: false, idempotent: true, openWorld: false },
    requiresWorkspace: true,
    supportsRollback: true,
    supportsParallel: true,
    resourceLocks: ['path:{path}', 'parent-chain:{path}'],
    permissionClass: 'write',
    activity: {
      running: 'Criando pasta {path}',
      completed: 'Pasta criada: {path}',
      failed: 'Falha ao criar pasta {path}',
    },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'process.start',
    name: 'start_process',
    title: 'Iniciar processo',
    category: 'process',
    description: 'Inicia um processo persistente associado ao run, retorna processId/PID e permite acompanhamento, leitura de saída e encerramento posterior.',
    whenToUse: [
      'Para servidores de desenvolvimento e processos que permanecem ativos.',
      'Quando run_command não deve aguardar o processo encerrar.',
    ],
    whenNotToUse: [
      'Não usar para comandos curtos e finitos que run_command consegue concluir diretamente.',
      'Não usar para abrir URL ou aplicação visual; use open_instance.',
    ],
    inputSchema: schemaObject({
      command: { type: 'string' },
    }, ['command']),
    outputSchema: schemaObject({
      processId: { type: 'string' },
      pid: { type: 'number' },
      status: { type: 'string' },
    }, ['processId', 'pid', 'status']),
    examples: ['Iniciar npm run dev e continuar o run enquanto o servidor permanece ativo.'],
    failureModes: ['Comando bloqueado por policy.', 'Executável ausente.', 'Falha ao iniciar processo.'],
    sideEffects: ['Cria processo local persistente gerenciado pelo Auto CodeZ.'],
    annotations: { readOnly: false, destructive: false, idempotent: false, openWorld: false },
    requiresWorkspace: true,
    supportsRollback: true,
    supportsParallel: true,
    resourceLocks: [],
    permissionClass: 'sensitive',
    activity: {
      running: 'Iniciando processo',
      completed: 'Processo iniciado',
      failed: 'Falha ao iniciar processo',
    },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'process.read_output',
    name: 'read_process_output',
    title: 'Ler saída do processo',
    category: 'process',
    description: 'Lê stdout/stderr já capturados de um processo persistente usando cursor monotônico, sem bloquear e sem repetir saída já consumida quando afterSequence é informado.',
    whenToUse: ['Para acompanhar logs de servidor, watcher ou job persistente.', 'Para obter somente output novo desde a leitura anterior.'],
    whenNotToUse: ['Não usar para esperar término; use wait_process.', 'Não usar para processo externo não gerenciado pelo Auto CodeZ.'],
    inputSchema: schemaObject({ processId: { type: 'string' }, afterSequence: { type: 'number' } }, ['processId', 'afterSequence']),
    outputSchema: schemaObject({ events: { type: 'array' }, nextSequence: { type: 'number' }, truncated: { type: 'boolean' } }, ['events', 'nextSequence', 'truncated']),
    examples: ['Ler logs novos do servidor iniciado por start_process.'],
    failureModes: ['processId desconhecido.', 'Processo pertence a outro projeto.', 'Cursor inválido.'],
    sideEffects: [],
    annotations: { readOnly: true, destructive: false, idempotent: true, openWorld: false },
    requiresWorkspace: true,
    supportsRollback: false,
    supportsParallel: true,
    resourceLocks: [],
    permissionClass: 'read',
    activity: { running: 'Lendo saída do processo', completed: 'Saída do processo lida', failed: 'Falha ao ler saída do processo' },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'process.wait',
    name: 'wait_process',
    title: 'Aguardar processo',
    category: 'process',
    description: 'Aguarda um processo persistente alcançar estado terminal até timeoutMs, sem matar o processo quando o timeout expira.',
    whenToUse: ['Para aguardar build/job persistente terminar.', 'Para polling controlado do lifecycle do processo.'],
    whenNotToUse: ['Não usar para ler logs; use read_process_output.', 'Não usar para encerrar processo; use stop_process.'],
    inputSchema: schemaObject({ processId: { type: 'string' }, timeoutMs: { type: 'number' } }, ['processId', 'timeoutMs']),
    outputSchema: schemaObject({ id: { type: 'string' }, status: { type: 'string' } }, ['id', 'status']),
    examples: ['Aguardar até 2000 ms pelo término de um build persistente.'],
    failureModes: ['processId desconhecido.', 'Processo pertence a outro projeto.', 'timeoutMs inválido.'],
    sideEffects: [],
    annotations: { readOnly: true, destructive: false, idempotent: true, openWorld: false },
    requiresWorkspace: true,
    supportsRollback: false,
    supportsParallel: true,
    resourceLocks: [],
    permissionClass: 'read',
    activity: { running: 'Aguardando processo', completed: 'Estado do processo atualizado', failed: 'Falha ao aguardar processo' },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'process.wait_for_port',
    name: 'wait_for_port',
    title: 'Aguardar porta local',
    category: 'process',
    description: 'Aguarda uma porta TCP loopback aceitar conexões enquanto o processo persistente gerenciado continua vivo, comprovando readiness local antes de abrir preview ou continuar validações dependentes do servidor.',
    whenToUse: ['Depois de start_process para servidor dev/local.', 'Antes de abrir preview que depende de uma porta realmente pronta.'],
    whenNotToUse: ['Não usar como scanner de rede.', 'Não usar para hosts remotos ou processos não gerenciados.'],
    inputSchema: schemaObject({
      processId: { type: 'string' },
      port: { type: 'number' },
      timeoutMs: { type: 'number' },
      host: { type: 'string', enum: ['localhost', '127.0.0.1', '::1'] },
    }, ['processId', 'port', 'timeoutMs', 'host']),
    outputSchema: schemaObject({
      processId: { type: 'string' },
      host: { type: 'string' },
      port: { type: 'number' },
      ready: { type: 'boolean' },
      waitedMs: { type: 'number' },
    }, ['processId', 'host', 'port', 'ready', 'waitedMs']),
    examples: ['Aguardar localhost:5173 depois de iniciar npm run dev.'],
    failureModes: ['Porta inválida.', 'Host não-loopback.', 'Processo pertence a outro projeto.', 'Processo encerrou antes do readiness.', 'Timeout de readiness.'],
    sideEffects: [],
    annotations: { readOnly: true, destructive: false, idempotent: true, openWorld: false },
    requiresWorkspace: true,
    supportsRollback: false,
    supportsParallel: true,
    resourceLocks: [],
    permissionClass: 'read',
    activity: { running: 'Aguardando porta local', completed: 'Porta local disponível', failed: 'Porta local indisponível' },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'process.stop',
    name: 'stop_process',
    title: 'Encerrar processo',
    category: 'process',
    description: 'Encerra um processo persistente gerenciado e sua árvore de filhos, preservando o estado terminal para inspeção posterior.',
    whenToUse: ['Para encerrar servidor dev, watcher ou job persistente.', 'Para limpar processo iniciado anteriormente pelo agente.'],
    whenNotToUse: ['Não usar em processo externo ao registry.', 'Não usar apenas para verificar estado; use wait_process ou list_processes.'],
    inputSchema: schemaObject({ processId: { type: 'string' } }, ['processId']),
    outputSchema: schemaObject({ id: { type: 'string' }, status: { type: 'string' } }, ['id', 'status']),
    examples: ['Parar o servidor dev depois da validação.'],
    failureModes: ['processId desconhecido.', 'Processo pertence a outro projeto.', 'Falha ao encerrar árvore de processos.'],
    sideEffects: ['Encerra processo local persistente e seus filhos.'],
    annotations: { readOnly: false, destructive: true, idempotent: true, openWorld: false },
    requiresWorkspace: true,
    supportsRollback: false,
    supportsParallel: true,
    resourceLocks: ['process:{processId}'],
    permissionClass: 'sensitive',
    activity: { running: 'Encerrando processo', completed: 'Processo encerrado', failed: 'Falha ao encerrar processo' },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'process.list',
    name: 'list_processes',
    title: 'Listar processos',
    category: 'process',
    description: 'Lista processos persistentes gerenciados pertencentes ao workspace ativo e seus estados de lifecycle.',
    whenToUse: ['Para descobrir processId e estado de processos já iniciados.', 'Para auditar servidores/watchers ativos no workspace.'],
    whenNotToUse: ['Não usar para enumerar processos arbitrários do sistema operacional.'],
    inputSchema: schemaObject({}, []),
    outputSchema: schemaObject({ processes: { type: 'array' } }, ['processes']),
    examples: ['Listar servidores persistentes ativos antes de iniciar outro.'],
    failureModes: ['Runtime de processos indisponível.'],
    sideEffects: [],
    annotations: { readOnly: true, destructive: false, idempotent: true, openWorld: false },
    requiresWorkspace: true,
    supportsRollback: false,
    supportsParallel: true,
    resourceLocks: [],
    permissionClass: 'read',
    activity: { running: 'Listando processos', completed: 'Processos listados', failed: 'Falha ao listar processos' },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'instance.open',
    name: 'open_instance',
    title: 'Abrir instância',
    category: 'instance',
    description: 'Abre e registra uma instância visual ou navegável, como aplicação, URL, arquivo, pasta ou preview, retornando instanceId para lifecycle posterior.',
    whenToUse: [
      'Quando o usuário pede para abrir algo.',
      'Quando o agente precisa abrir preview/URL/aplicação para validar resultado.',
    ],
    whenNotToUse: [
      'Não usar para processo headless sem superfície visual.',
      'Não substituir start_process quando o objetivo é manter servidor/processo de backend ativo.',
    ],
    inputSchema: schemaObject({
      kind: { type: 'string', enum: ['application', 'url', 'file', 'folder', 'preview'] },
      target: { type: 'string' },
    }, ['kind', 'target']),
    outputSchema: schemaObject({
      instanceId: { type: 'string' },
      status: { type: 'string' },
    }, ['instanceId', 'status']),
    examples: [
      'Abrir http://localhost:5173 depois que wait_for_port confirmar readiness.',
      'Abrir a pasta do projeto quando solicitado pelo usuário.',
    ],
    failureModes: ['Target inválido.', 'Aplicação/protocolo não associado.', 'Bloqueio de policy/scope.'],
    sideEffects: ['Abre uma instância local visível ou navegável.'],
    annotations: { readOnly: false, destructive: false, idempotent: false, openWorld: true },
    requiresWorkspace: false,
    supportsRollback: false,
    supportsParallel: true,
    resourceLocks: [],
    permissionClass: 'external',
    activity: {
      running: 'Abrindo {label}',
      completed: 'Aberto {label}',
      failed: 'Falha ao abrir {label}',
    },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'instance.status',
    name: 'instance_status',
    title: 'Consultar instância',
    category: 'instance',
    description: 'Consulta estado, target e capacidades reais de foco/fechamento de uma instância gerenciada do workspace ativo.',
    whenToUse: ['Antes de agir sobre uma instância quando o estado atual importa.', 'Para confirmar se uma instância continua aberta.'],
    whenNotToUse: ['Não usar para inspecionar conteúdo visual; capture/inspect pertencem a uma fase futura.'],
    inputSchema: schemaObject({ instanceId: { type: 'string' } }, ['instanceId']),
    outputSchema: schemaObject({ instanceId: { type: 'string' }, status: { type: 'string' }, capabilities: { type: 'object' } }, ['instanceId', 'status', 'capabilities']),
    examples: ['Consultar se o preview aberto ainda está ativo e controlável.'],
    failureModes: ['Instância inexistente.', 'Instância pertence a outro workspace.'],
    sideEffects: [],
    annotations: { readOnly: true, destructive: false, idempotent: true, openWorld: false },
    requiresWorkspace: false,
    supportsRollback: false,
    supportsParallel: true,
    resourceLocks: [],
    permissionClass: 'read',
    activity: { running: 'Consultando instância', completed: 'Instância consultada', failed: 'Falha ao consultar instância' },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'instance.capture',
    name: 'capture_instance',
    title: 'Capturar preview',
    category: 'instance',
    description: 'Captura PNG real de um preview gerenciado do workspace ativo; armazena os bytes no AttachmentStore e retorna referência verificável sem incorporar base64 ao resultado textual.',
    whenToUse: ['Depois de abrir um preview gerenciado, quando houver necessidade de observar visualmente a página.', 'Para registrar evidência visual de uma interface em execução.'],
    whenNotToUse: ['Não captura janelas externas sem controle do Auto CodeZ.', 'Não alegar análise visual sem entrega comprovada a um modelo com visão.'],
    inputSchema: schemaObject({ instanceId: { type: 'string' } }, ['instanceId']),
    outputSchema: schemaObject({ type: { type: 'string' }, instanceId: { type: 'string' }, artifact: { type: 'object' }, visualAnalysis: { type: 'string' } }, ['type', 'instanceId', 'artifact', 'visualAnalysis']),
    examples: ['Capturar preview de localhost após open_instance e wait_for_port.'],
    failureModes: ['Instância inexistente.', 'Instância de outro projeto.', 'Preview fechado.', 'Imagem vazia, inválida ou maior que o limite.', 'Armazenamento de anexos indisponível.'],
    sideEffects: ['Persiste artefato PNG no armazenamento local verificado.'],
    annotations: { readOnly: false, destructive: false, idempotent: false, openWorld: false },
    requiresWorkspace: false,
    supportsRollback: false,
    supportsParallel: false,
    resourceLocks: [],
    permissionClass: 'sensitive',
    activity: { running: 'Capturando preview', completed: 'Preview capturado', failed: 'Falha ao capturar preview' },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'instance.inspect',
    name: 'inspect_instance',
    title: 'Inspecionar preview',
    category: 'instance',
    description: 'Consulta um snapshot estrutural limitado de texto e links visíveis de um preview gerenciado; não equivale a análise visual.',
    whenToUse: ['Conferir títulos, texto e links de um preview controlado.'],
    whenNotToUse: ['Não usar para afirmar cor, posição ou aparência visual de pixels.'],
    inputSchema: schemaObject({ instanceId: { type: 'string' } }, ['instanceId']),
    outputSchema: schemaObject({ instanceId: { type: 'string' }, title: { type: 'string' }, url: { type: 'string' }, text: { type: 'string' }, headings: { type: 'array' }, links: { type: 'array' } }, ['instanceId', 'title', 'url', 'text', 'headings', 'links']),
    examples: ['Ler títulos e links presentes no preview.'],
    failureModes: ['Instância fechada ou de outro projeto.','Preview sem suporte a inspeção.'],
    sideEffects: [],
    annotations: { readOnly: true, destructive: false, idempotent: true, openWorld: false },
    requiresWorkspace: false,
    supportsRollback: false,
    supportsParallel: true,
    resourceLocks: [],
    permissionClass: 'read',
    activity: { running: 'Inspecionando preview', completed: 'Preview inspecionado', failed: 'Falha ao inspecionar preview' },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'instance.focus',
    name: 'focus_instance',
    title: 'Focar instância',
    category: 'instance',
    description: 'Foca uma instância apenas quando o adapter da plataforma oferece controle real de foco.',
    whenToUse: ['Quando um preview gerenciado precisa voltar ao primeiro plano.'],
    whenNotToUse: ['Não fingir foco para URL, arquivo, pasta ou aplicação abertos externamente sem handle controlável.'],
    inputSchema: schemaObject({ instanceId: { type: 'string' } }, ['instanceId']),
    outputSchema: schemaObject({ instanceId: { type: 'string' }, status: { type: 'string' } }, ['instanceId', 'status']),
    examples: ['Trazer o preview gerenciado de volta ao foco.'],
    failureModes: ['Instância inexistente.', 'Instância fechada.', 'Controle de foco indisponível.', 'Instância pertence a outro workspace.'],
    sideEffects: ['Altera o foco de uma superfície controlada pelo Auto CodeZ.'],
    annotations: { readOnly: false, destructive: false, idempotent: true, openWorld: false },
    requiresWorkspace: false,
    supportsRollback: false,
    supportsParallel: false,
    resourceLocks: [],
    permissionClass: 'write',
    activity: { running: 'Focando instância', completed: 'Instância focada', failed: 'Falha ao focar instância' },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'instance.close',
    name: 'close_instance',
    title: 'Fechar instância',
    category: 'instance',
    description: 'Fecha uma instância somente quando o adapter da plataforma oferece controle real de fechamento.',
    whenToUse: ['Para encerrar preview gerenciado aberto pelo Auto CodeZ.'],
    whenNotToUse: ['Não alegar fechamento de superfícies externas sem handle controlável.'],
    inputSchema: schemaObject({ instanceId: { type: 'string' } }, ['instanceId']),
    outputSchema: schemaObject({ instanceId: { type: 'string' }, status: { type: 'string' } }, ['instanceId', 'status']),
    examples: ['Fechar o preview após concluir a validação.'],
    failureModes: ['Instância inexistente.', 'Controle de fechamento indisponível.', 'Instância pertence a outro workspace.'],
    sideEffects: ['Fecha uma superfície controlada pelo Auto CodeZ.'],
    annotations: { readOnly: false, destructive: false, idempotent: true, openWorld: false },
    requiresWorkspace: false,
    supportsRollback: false,
    supportsParallel: false,
    resourceLocks: [],
    permissionClass: 'sensitive',
    activity: { running: 'Fechando instância', completed: 'Instância fechada', failed: 'Falha ao fechar instância' },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'instance.list',
    name: 'list_instances',
    title: 'Listar instâncias',
    category: 'instance',
    description: 'Lista somente as instâncias gerenciadas pertencentes ao workspace ativo.',
    whenToUse: ['Para descobrir instanceId, lifecycle e capacidades das superfícies já abertas no workspace.'],
    whenNotToUse: ['Não usar para enumerar janelas ou aplicações arbitrárias do sistema operacional.'],
    inputSchema: schemaObject({}, []),
    outputSchema: schemaObject({ instances: { type: 'array' } }, ['instances']),
    examples: ['Listar previews gerenciados antes de abrir outro.'],
    failureModes: ['Runtime de instâncias indisponível.'],
    sideEffects: [],
    annotations: { readOnly: true, destructive: false, idempotent: true, openWorld: false },
    requiresWorkspace: false,
    supportsRollback: false,
    supportsParallel: true,
    resourceLocks: [],
    permissionClass: 'read',
    activity: { running: 'Listando instâncias', completed: 'Instâncias listadas', failed: 'Falha ao listar instâncias' },
    version: 1,
  },
] as const;
