import type { CapabilityContract } from './contracts';

const schemaObject = (properties: Record<string, unknown>, required: string[] = []): Record<string, unknown> => ({
  type: 'object',
  properties,
  required,
  additionalProperties: false,
});

export const AGENT_CORE_V2_BASELINE_CAPABILITIES: readonly CapabilityContract[] = [
  {
    contractVersion: 1,
    id: 'workspace.create_file',
    name: 'create_file',
    title: 'Criar arquivo',
    category: 'workspace',
    description: 'Cria um novo arquivo de texto no workspace real. Diretórios pais ausentes são criados automaticamente. A operação deve ser atômica, verificada e registrada no Recovery Journal.',
    whenToUse: [
      'Quando o resultado exige um novo arquivo conhecido.',
      'Quando criar o primeiro arquivo também pode materializar a estrutura de diretórios pais.',
    ],
    whenNotToUse: [
      'Não usar para substituir silenciosamente arquivo existente.',
      'Não usar shell redirection quando esta capability representa a operação.',
    ],
    inputSchema: schemaObject({
      path: { type: 'string' },
      content: { type: 'string' },
    }, ['path', 'content']),
    outputSchema: schemaObject({
      path: { type: 'string' },
      hash: { type: 'string' },
      bytes: { type: 'number' },
    }, ['path', 'hash', 'bytes']),
    examples: [
      'Criar Desktop/Carros/index.html com o HTML inicial.',
      'Criar src/components/Hero.tsx; src/components é criado automaticamente se não existir.',
    ],
    failureModes: [
      'Path fora do escopo permitido.',
      'Arquivo destino já existe quando overwrite não foi explicitamente permitido.',
      'Falha de escrita atômica ou verificação pós-write.',
    ],
    sideEffects: ['Cria o arquivo no workspace real e pode criar diretórios pais.'],
    annotations: { readOnly: false, destructive: false, idempotent: false, openWorld: false },
    requiresWorkspace: true,
    supportsRollback: true,
    supportsParallel: true,
    resourceLocks: ['path:{path}', 'parent-chain:{path}'],
    permissionClass: 'write',
    activity: {
      running: 'Criando {path}',
      completed: 'Criado {path}',
      failed: 'Falha ao criar {path}',
    },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'workspace.create_folder',
    name: 'create_folder',
    title: 'Criar pasta',
    category: 'workspace',
    description: 'Cria uma pasta real no workspace quando o diretório em si faz parte do resultado ou precisa existir vazio. Não substitui create_file, que continua criando diretórios pais automaticamente.',
    whenToUse: [
      'Quando o usuário pediu explicitamente uma pasta.',
      'Quando uma pasta vazia é parte do resultado.',
      'Quando uma etapa posterior depende da existência explícita do diretório antes de criar arquivos.',
    ],
    whenNotToUse: [
      'Não chamar apenas para preparar diretórios pais de create_file.',
      'Não usar mkdir via shell quando esta capability representa a intenção.',
    ],
    inputSchema: schemaObject({ path: { type: 'string' } }, ['path']),
    outputSchema: schemaObject({ path: { type: 'string' }, created: { type: 'boolean' } }, ['path', 'created']),
    examples: [
      'Criar assets/uploads como pasta vazia.',
      'Criar Desktop/Carros antes de abrir a pasta a pedido do usuário.',
    ],
    failureModes: [
      'Path fora do escopo.',
      'Conflito com arquivo existente.',
      'Falha de filesystem/verificação.',
    ],
    sideEffects: ['Cria um diretório no workspace real.'],
    annotations: { readOnly: false, destructive: false, idempotent: true, openWorld: false },
    requiresWorkspace: true,
    supportsRollback: true,
    supportsParallel: true,
    resourceLocks: ['path:{path}', 'parent-chain:{path}'],
    permissionClass: 'write',
    activity: {
      running: 'Criando pasta {path}',
      completed: 'Pasta criada: {path}',
      failed: 'Falha ao criar pasta {path}',
    },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'process.start',
    name: 'start_process',
    title: 'Iniciar processo',
    category: 'process',
    description: 'Inicia um processo persistente associado ao run, retorna processId/PID e permite acompanhamento, leitura de saída e encerramento posterior.',
    whenToUse: [
      'Para servidores de desenvolvimento e processos que permanecem ativos.',
      'Quando run_command não deve aguardar o processo encerrar.',
    ],
    whenNotToUse: [
      'Não usar para comandos curtos e finitos que run_command consegue concluir diretamente.',
      'Não usar para abrir URL ou aplicação visual; use open_instance.',
    ],
    inputSchema: schemaObject({
      command: { type: 'string' },
      cwd: { type: 'string' },
    }, ['command']),
    outputSchema: schemaObject({
      processId: { type: 'string' },
      pid: { type: 'number' },
      status: { type: 'string' },
    }, ['processId', 'pid', 'status']),
    examples: ['Iniciar npm run dev e continuar o run enquanto o servidor permanece ativo.'],
    failureModes: ['Comando bloqueado por policy.', 'Executável ausente.', 'Falha ao iniciar processo.'],
    sideEffects: ['Cria processo local persistente gerenciado pelo Auto CodeZ.'],
    annotations: { readOnly: false, destructive: false, idempotent: false, openWorld: false },
    requiresWorkspace: true,
    supportsRollback: true,
    supportsParallel: true,
    resourceLocks: [],
    permissionClass: 'sensitive',
    activity: {
      running: 'Iniciando processo',
      completed: 'Processo iniciado',
      failed: 'Falha ao iniciar processo',
    },
    version: 1,
  },
  {
    contractVersion: 1,
    id: 'instance.open',
    name: 'open_instance',
    title: 'Abrir instância',
    category: 'instance',
    description: 'Abre e registra uma instância visual ou navegável, como aplicação, URL, arquivo, pasta ou preview, retornando instanceId para lifecycle posterior.',
    whenToUse: [
      'Quando o usuário pede para abrir algo.',
      'Quando o agente precisa abrir preview/URL/aplicação para validar resultado.',
    ],
    whenNotToUse: [
      'Não usar para processo headless sem superfície visual.',
      'Não substituir start_process quando o objetivo é manter servidor/processo de backend ativo.',
    ],
    inputSchema: schemaObject({
      kind: { type: 'string', enum: ['application', 'url', 'file', 'folder', 'preview'] },
      target: { type: 'string' },
    }, ['kind', 'target']),
    outputSchema: schemaObject({
      instanceId: { type: 'string' },
      status: { type: 'string' },
    }, ['instanceId', 'status']),
    examples: [
      'Abrir http://localhost:5173 depois que wait_for_port confirmar readiness.',
      'Abrir a pasta do projeto quando solicitado pelo usuário.',
    ],
    failureModes: ['Target inválido.', 'Aplicação/protocolo não associado.', 'Bloqueio de policy/scope.'],
    sideEffects: ['Abre uma instância local visível ou navegável.'],
    annotations: { readOnly: false, destructive: false, idempotent: false, openWorld: true },
    requiresWorkspace: false,
    supportsRollback: true,
    supportsParallel: true,
    resourceLocks: [],
    permissionClass: 'external',
    activity: {
      running: 'Abrindo {label}',
      completed: 'Aberto {label}',
      failed: 'Falha ao abrir {label}',
    },
    version: 1,
  },
] as const;
