const STYLE_ID = 'auto-codez-ui-polish';
const RECOVERY_ID = 'ac-ai-recovery';
const APP_SETTINGS_ID = 'ac-app-settings';
const APP_SETTINGS_MODAL_ID = 'ac-app-settings-modal';

type IconName = 'message-circle-plus' | 'folder' | 'blocks' | 'git-branch' | 'square-terminal' | 'key-round' | 'plus' | 'sparkles' | 'settings';
const ICON_PATHS: Record<IconName, string[]> = {
  'message-circle-plus': ['M7.9 20A9 9 0 1 0 4 16.1L2 22Z', 'M8 12h8', 'M12 8v8'],
  folder: ['M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z'],
  blocks: ['M7 3H4a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1Z', 'M20 3h-3a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1Z', 'M20 16h-3a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1Z', 'M7 16H4a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1Z'],
  'git-branch': ['M6 3v12', 'M18 9V3', 'M6 15a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z', 'M18 3a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z', 'M6 15c0-3 3-6 9-6'],
  'square-terminal': ['m7 11 3 3-3 3', 'm13 17 4 0', 'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Z'],
  'key-round': ['m15.5 7.5 3-3', 'm17 5 2 2', 'M11 14a5 5 0 1 1-1-7.9A5 5 0 0 1 11 14Z', 'M16 8l-5 5'],
  plus: ['M5 12h14', 'M12 5v14'],
  sparkles: ['m12 3-1.9 5.8a2 2 0 0 1-1.3 1.3L3 12l5.8 1.9a2 2 0 0 1 1.3 1.3L12 21l1.9-5.8a2 2 0 0 1 1.3-1.3L21 12l-5.8-1.9a2 2 0 0 1-1.3-1.3Z', 'M5 3v4', 'M19 17v4', 'M3 5h4', 'M17 19h4'],
  settings: ['M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Z', 'M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-1.6 1.5-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.5V20h-2.4v-.4a1.7 1.7 0 0 0-1-1.5 1.7 1.7 0 0 0-1.9.3l-.1.1-1.5-1.5.1-.1a1.7 1.7 0 0 0 .3-1.9 1.7 1.7 0 0 0-1.5-1H6v-2.1h.3a1.7 1.7 0 0 0 1.5-1 1.7 1.7 0 0 0-.3-1.9l-.1-.1 1.5-1.5.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.5V4h2.4v.4a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.9-.3l.1-.1 1.5 1.5-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.5 1h.3v2.1h-.3a1.7 1.7 0 0 0-1.5 1Z']
};
function icon(name: IconName, size = 18): SVGSVGElement {
  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
  svg.setAttribute('viewBox', '0 0 24 24'); svg.setAttribute('width', String(size)); svg.setAttribute('height', String(size));
  svg.setAttribute('fill', 'none'); svg.setAttribute('stroke', 'currentColor'); svg.setAttribute('stroke-width', '2'); svg.setAttribute('stroke-linecap', 'round'); svg.setAttribute('stroke-linejoin', 'round'); svg.setAttribute('aria-hidden', 'true'); svg.classList.add('ac-lucide-icon');
  for (const d of ICON_PATHS[name]) { const path = document.createElementNS('http://www.w3.org/2000/svg', 'path'); path.setAttribute('d', d); svg.appendChild(path); }
  return svg;
}
function installStyle(): void {
  if (document.getElementById(STYLE_ID)) return;
  const style = document.createElement('style'); style.id = STYLE_ID; style.textContent = `
    .chat-item{position:relative;padding-right:64px!important}.chat-settings,.chat-delete{width:26px!important;height:26px!important;position:absolute;top:50%;transform:translateY(-50%);margin:0!important;border:0!important;border-radius:7px!important;background:transparent!important;font-size:0!important;opacity:0!important}.chat-settings{right:34px;color:#aeb7c4!important}.chat-delete{right:7px;color:#c76f78!important}.chat-item:hover .chat-settings,.chat-item:hover .chat-delete,.chat-settings:focus-visible,.chat-delete:focus-visible{opacity:1!important}
    .message.streaming .message-label{display:flex;align-items:center;gap:7px}.message.streaming .message-label:before{content:"";width:6px;height:6px;border-radius:50%;background:#aeb9c8;box-shadow:0 0 0 4px #aeb9c812;animation:ac-pulse 1.2s ease-in-out infinite}.composer-hint.ac-busy{opacity:.35}.chat-header{position:relative}.chat-header h1{max-width:min(48vw,520px);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.header-actions{align-items:center}.empty-panel{margin:8px 2px;padding:18px 12px!important;border:1px solid #1b212b;border-radius:10px;background:#0f1319;color:#6d7785!important}.empty-panel:empty{display:none}.plugin-card{transition:border-color .16s,background .16s,transform .16s}.plugin-card:hover{border-color:#303845;background:linear-gradient(145deg,#131820,#0f1319);transform:translateY(-1px)}
    .ac-lucide-icon{display:block;flex:0 0 auto;color:inherit}.rail-button{display:inline-flex!important;align-items:center!important;justify-content:center!important;color:inherit!important}.rail-button .ac-lucide-icon{pointer-events:none}.new-chat-icon,.attach-button,.intelligence-brain,.git-icon{display:inline-flex!important;align-items:center!important;justify-content:center!important;background:none!important;-webkit-mask:none!important;mask:none!important}.new-chat-icon .ac-lucide-icon,.attach-button .ac-lucide-icon,.intelligence-brain .ac-lucide-icon,.git-icon .ac-lucide-icon{width:18px;height:18px}.git-icon{width:18px!important;height:18px!important;border:0!important;border-radius:0!important}.brand-mark{border:0!important;box-shadow:none!important}.brand-mark:before,.brand-mark:after{display:none!important}
    .topbar-actions>[data-action="new-chat"],.topbar-actions>[data-action="ai-settings"]{display:none!important}#${APP_SETTINGS_ID}{display:inline-flex;align-items:center;justify-content:center;width:34px;height:34px;padding:0;border:0;border-radius:9px;color:#aeb7c4;background:transparent;cursor:pointer}#${APP_SETTINGS_ID}:hover{color:#eef2f6;background:#171d26}#${APP_SETTINGS_ID} .ac-lucide-icon{width:17px;height:17px}.chat-title-row .gear{display:none!important}
    #${APP_SETTINGS_MODAL_ID}{position:fixed;inset:0;z-index:10000;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.52);padding:24px}#${APP_SETTINGS_MODAL_ID}[hidden]{display:none}.ac-app-settings-dialog{width:min(560px,100%);border:1px solid #2a313d;border-radius:14px;background:#10151c;color:#e8edf3;box-shadow:0 24px 70px rgba(0,0,0,.45);overflow:hidden}.ac-app-settings-head{display:flex;align-items:center;justify-content:space-between;padding:18px 20px;border-bottom:1px solid #202731}.ac-app-settings-head h2{margin:0;font-size:16px;font-weight:650}.ac-app-settings-close{width:30px;height:30px;border:0;border-radius:8px;background:transparent;color:#8f9aaa;font-size:20px;cursor:pointer}.ac-app-settings-close:hover{background:#1a2029;color:#eef2f6}.ac-app-settings-body{padding:20px;color:#98a3b2;font-size:13px;line-height:1.55}.ac-app-settings-section{padding:12px 0;border-top:1px solid #202731}.ac-app-settings-section:first-child{border-top:0;padding-top:0}.ac-app-settings-section strong{display:block;color:#dce2e9;margin-bottom:4px}
    @keyframes ac-pulse{0%,100%{opacity:.45;transform:scale(.9)}50%{opacity:1;transform:scale(1)}}@media(prefers-reduced-motion:reduce){.message.streaming .message-label:before{animation:none}}
  `; document.head.appendChild(style);
}
function openApiKeyManager(): void { document.querySelector<HTMLButtonElement>('.api-key-rail-button')?.click(); }
function openAppSettings(): void {
  let modal=document.getElementById(APP_SETTINGS_MODAL_ID); if(!modal){ modal=document.createElement('div'); modal.id=APP_SETTINGS_MODAL_ID; modal.hidden=true; modal.innerHTML='<div class="ac-app-settings-dialog" role="dialog" aria-modal="true"><div class="ac-app-settings-head"><h2>Configurações do aplicativo</h2><button class="ac-app-settings-close" type="button" aria-label="Fechar">×</button></div><div class="ac-app-settings-body"><div class="ac-app-settings-section"><strong>Auto CodeZ</strong><span>As configurações gerais do aplicativo ficarão concentradas neste painel.</span></div><div class="ac-app-settings-section"><strong>Próximas configurações</strong><span>Aparência, comportamento, editor, notificações e outras preferências serão adicionadas aqui.</span></div></div></div>'; document.body.appendChild(modal); modal.addEventListener('click',(event)=>{if(event.target===modal||(event.target as HTMLElement).closest('.ac-app-settings-close')) modal!.hidden=true;}); } modal.hidden=false;
}
function ensureAppSettingsButton(): void { const actions=document.querySelector<HTMLElement>('.topbar-actions'); if(!actions||document.getElementById(APP_SETTINGS_ID))return; const button=document.createElement('button'); button.id=APP_SETTINGS_ID; button.type='button'; button.title='Configurações do aplicativo'; button.setAttribute('aria-label','Configurações do aplicativo'); button.appendChild(icon('settings',17)); button.addEventListener('click',openAppSettings); actions.appendChild(button); }
function replaceIcon(element: Element,name: IconName,size=18): void { const target=element as HTMLElement; if(target.querySelector(':scope > .ac-lucide-icon'))return; target.querySelectorAll(':scope > *').forEach(child=>child.remove()); target.appendChild(icon(name,size)); }
function syncLucideIcons(): void {
  document.querySelectorAll<HTMLElement>('.rail-button').forEach(button=>{const panel=button.getAttribute('data-panel'); const name:IconName=panel==='plugins'?'blocks':panel==='projects'?'folder':'message-circle-plus'; replaceIcon(button,name);});
  document.querySelectorAll<HTMLElement>('.api-key-rail-button').forEach(button=>replaceIcon(button,'key-round'));
  document.querySelectorAll<HTMLElement>('.new-chat-icon').forEach(element=>replaceIcon(element,'message-circle-plus'));
  document.querySelectorAll<HTMLElement>('.attach-button').forEach(element=>replaceIcon(element,'plus'));
  document.querySelectorAll<HTMLElement>('.intelligence-brain').forEach(element=>replaceIcon(element,'sparkles',16));
  document.querySelectorAll<HTMLElement>('.git-icon').forEach(element=>replaceIcon(element,'git-branch'));
  document.querySelectorAll<HTMLElement>('.terminal-icon').forEach(element=>replaceIcon(element,'square-terminal'));
}
function removeDuplicateChatGear(): void { document.querySelectorAll<HTMLElement>('.chat-title-row .gear').forEach(element=>element.remove()); }
function removeReasoningProfileFromChatSettings(): void { const modalRoot=document.querySelector<HTMLElement>('#modal-root'); if(!modalRoot)return; for(const element of Array.from(modalRoot.querySelectorAll<HTMLElement>('label,.field,.form-field,.setting-row,.setting-field,.modal-field,.modal-row'))){const text=element.textContent?.trim().toLowerCase()??''; if(text.includes('perfil de raciocínio')||text.includes('perfil de raciocinio'))element.remove();} }
function syncAiRecovery(): void { const header=document.querySelector<HTMLElement>('.chat-header'); if(!header)return; const providerText=header.querySelector<HTMLElement>('.provider-chip')?.textContent?.trim().toLowerCase()??''; const isUnconfigured=providerText.includes('ia não configurada'); let recovery=header.querySelector<HTMLButtonElement>(`#${RECOVERY_ID}`); if(!isUnconfigured){recovery?.remove();return;} if(!recovery){recovery=document.createElement('button'); recovery.id=RECOVERY_ID; recovery.className='ac-ai-recovery'; recovery.type='button'; recovery.textContent='Configurar IA'; recovery.title='Adicionar ou selecionar uma API key'; recovery.addEventListener('click',openApiKeyManager); header.querySelector('.header-actions')?.prepend(recovery);} }
function syncErrorState(): void { const activity=document.querySelector<HTMLElement>('#messages .activity-card'); if(!activity)return; activity.classList.toggle('ac-error-state',Boolean(activity.querySelector('.activity-line.error'))); }
function initialize(): void {
  installStyle(); ensureAppSettingsButton(); syncLucideIcons(); syncAiRecovery(); syncErrorState(); removeDuplicateChatGear(); removeReasoningProfileFromChatSettings();
  const header=document.querySelector<HTMLElement>('.chat-header'); if(header)new MutationObserver(()=>{syncAiRecovery();removeDuplicateChatGear();syncLucideIcons();}).observe(header,{childList:true,subtree:true,characterData:true});
  const messages=document.querySelector<HTMLElement>('#messages'); if(messages)new MutationObserver(syncErrorState).observe(messages,{childList:true,subtree:true});
  const modalRoot=document.querySelector<HTMLElement>('#modal-root'); if(modalRoot)new MutationObserver(()=>{removeReasoningProfileFromChatSettings();syncLucideIcons();}).observe(modalRoot,{childList:true,subtree:true,characterData:true});
  new MutationObserver(()=>{ensureAppSettingsButton();syncLucideIcons();}).observe(document.body,{childList:true,subtree:true});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initialize,{once:true}); else initialize();
